export type BuiltinPersonaId = 'minako' | 'souma';

export interface BuiltinPersona {
	id: BuiltinPersonaId;
	label: string;
	soulFilename: string;
}

export const BUILTIN_PERSONAS: BuiltinPersona[] = [
	{ id: 'minako', label: 'Minako', soulFilename: 'SOUL.md' },
	{ id: 'souma', label: 'Souma', soulFilename: 'SOUL_MAN.md' }
];

const VALID_BUILTIN_PERSONA_IDS = new Set<BuiltinPersonaId>(
	BUILTIN_PERSONAS.map((persona) => persona.id)
);

export function isBuiltinPersonaId(value: unknown): value is BuiltinPersonaId {
	return typeof value === 'string' && VALID_BUILTIN_PERSONA_IDS.has(value as BuiltinPersonaId);
}

/**
 * Builtin avatar assets kept their original `default`/`man` filename suffixes
 * (generated by `scripts/generate-project-icons.swift`); only the persona id
 * naming changed (`default`/`man` -> `minako`/`souma`).
 */
export function builtinPersonaAvatarSrc(id: BuiltinPersonaId, size: 96 | 192 | 384 = 192): string {
	const suffix = id === 'souma' ? '_man' : '';
	return `/project_avatar${suffix}_${size}.png`;
}

export function builtinPersonaAvatarSrcset(id: BuiltinPersonaId): string {
	return ([96, 192, 384] as const)
		.map((size) => `${builtinPersonaAvatarSrc(id, size)} ${size}w`)
		.join(', ');
}

export function builtinPersonaSoulFilename(id: BuiltinPersonaId): string {
	return id === 'souma' ? 'SOUL_MAN.md' : 'SOUL.md';
}

/** Migrates the legacy `app.iconVariant` field (`'default' | 'man'`) to a builtin persona id. */
export function migratePersonaIdFromIconVariant(iconVariant: unknown): BuiltinPersonaId {
	return iconVariant === 'man' ? 'souma' : 'minako';
}
