// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apigen

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ImageAttachmentMediaType.
const (
	Imagegif  ImageAttachmentMediaType = "image/gif"
	Imagejpeg ImageAttachmentMediaType = "image/jpeg"
	Imagepng  ImageAttachmentMediaType = "image/png"
	Imagewebp ImageAttachmentMediaType = "image/webp"
)

// Valid indicates whether the value is a known member of the ImageAttachmentMediaType enum.
func (e ImageAttachmentMediaType) Valid() bool {
	switch e {
	case Imagegif:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for MemoryChangeWireAction.
const (
	Create    MemoryChangeWireAction = "create"
	Supersede MemoryChangeWireAction = "supersede"
	Update    MemoryChangeWireAction = "update"
)

// Valid indicates whether the value is a known member of the MemoryChangeWireAction enum.
func (e MemoryChangeWireAction) Valid() bool {
	switch e {
	case Create:
		return true
	case Supersede:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for SessionDelegationStatus.
const (
	Cancelled SessionDelegationStatus = "cancelled"
	Completed SessionDelegationStatus = "completed"
	Failed    SessionDelegationStatus = "failed"
	Pending   SessionDelegationStatus = "pending"
	Running   SessionDelegationStatus = "running"
)

// Valid indicates whether the value is a known member of the SessionDelegationStatus enum.
func (e SessionDelegationStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	Active   SessionStatus = "active"
	Archived SessionStatus = "archived"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	default:
		return false
	}
}

// Defines values for TranscriptItemType.
const (
	Assistant TranscriptItemType = "assistant"
	Memory    TranscriptItemType = "memory"
	Reasoning TranscriptItemType = "reasoning"
	System    TranscriptItemType = "system"
	Tool      TranscriptItemType = "tool"
	User      TranscriptItemType = "user"
)

// Valid indicates whether the value is a known member of the TranscriptItemType enum.
func (e TranscriptItemType) Valid() bool {
	switch e {
	case Assistant:
		return true
	case Memory:
		return true
	case Reasoning:
		return true
	case System:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceFileImageContentKind.
const (
	Image WorkspaceFileImageContentKind = "image"
)

// Valid indicates whether the value is a known member of the WorkspaceFileImageContentKind enum.
func (e WorkspaceFileImageContentKind) Valid() bool {
	switch e {
	case Image:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceFileTextContentKind.
const (
	Text WorkspaceFileTextContentKind = "text"
)

// Valid indicates whether the value is a known member of the WorkspaceFileTextContentKind enum.
func (e WorkspaceFileTextContentKind) Valid() bool {
	switch e {
	case Text:
		return true
	default:
		return false
	}
}

// ChangeSessionWorkspaceRequest defines model for ChangeSessionWorkspaceRequest.
type ChangeSessionWorkspaceRequest struct {
	// WorkspacePath Absolute filesystem path for the new workspace root.
	WorkspacePath string `json:"workspace_path"`
}

// CompactMemoryPreviewResponse defines model for CompactMemoryPreviewResponse.
type CompactMemoryPreviewResponse struct {
	Active      int                `json:"active"`
	MaxMemories int                `json:"max_memories"`
	ToForget    []MemoryResource   `json:"to_forget"`
	ToMerge     [][]MemoryResource `json:"to_merge"`
}

// CreateMemoryRequest defines model for CreateMemoryRequest.
type CreateMemoryRequest struct {
	BaseWeight *float32 `json:"base_weight,omitempty"`
	Content    string   `json:"content"`
	Kind       *string  `json:"kind,omitempty"`
	Pinned     *bool    `json:"pinned,omitempty"`
}

// CreateSessionRequest Provide either `workspace_id` or `workspace_path`.
type CreateSessionRequest struct {
	// ModelId Optional model override; defaults to current config.
	ModelId *string `json:"model_id,omitempty"`

	// ProviderId Optional provider override; defaults to current config.
	ProviderId *string `json:"provider_id,omitempty"`

	// WorkspaceId Registered workspace identifier.
	WorkspaceId *string `json:"workspace_id,omitempty"`

	// WorkspacePath Absolute filesystem path for the workspace.
	WorkspacePath *string `json:"workspace_path,omitempty"`
}

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest struct {
	// WorkspacePath Absolute filesystem path for the workspace.
	WorkspacePath string `json:"workspace_path"`
}

// DoneEvent defines model for DoneEvent.
type DoneEvent struct {
	Type string `json:"type"`
}

// ErrorEvent defines model for ErrorEvent.
type ErrorEvent struct {
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
	Type    string  `json:"type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// ForkSessionRequest defines model for ForkSessionRequest.
type ForkSessionRequest struct {
	// WorkspacePath Absolute filesystem path for the forked session's workspace root.
	WorkspacePath string `json:"workspace_path"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ImageAttachment defines model for ImageAttachment.
type ImageAttachment struct {
	// Data Raw base64 payload without a data URL prefix. Each decoded image must be at most 4 MB.
	Data string `json:"data"`

	// Id Client-only identifier for UI attachment lists; not sent to CometMind.
	Id        *string                  `json:"id,omitempty"`
	MediaType ImageAttachmentMediaType `json:"media_type"`
	Name      *string                  `json:"name,omitempty"`
	Size      *int                     `json:"size,omitempty"`
}

// ImageAttachmentMediaType defines model for ImageAttachment.MediaType.
type ImageAttachmentMediaType string

// ListMemoriesResponse defines model for ListMemoriesResponse.
type ListMemoriesResponse struct {
	Memories []MemoryResource `json:"memories"`
}

// ListSkillsResponse defines model for ListSkillsResponse.
type ListSkillsResponse struct {
	Errors *[]string `json:"errors,omitempty"`
	Skills []Skill   `json:"skills"`
}

// MemoryChangeWire defines model for MemoryChangeWire.
type MemoryChangeWire struct {
	Action  MemoryChangeWireAction `json:"action"`
	Content string                 `json:"content"`
	Id      *string                `json:"id,omitempty"`
	Kind    string                 `json:"kind"`
}

// MemoryChangeWireAction defines model for MemoryChangeWire.Action.
type MemoryChangeWireAction string

// MemoryEmbeddingSettings defines model for MemoryEmbeddingSettings.
type MemoryEmbeddingSettings struct {
	ApiKey     *string `json:"api_key,omitempty"`
	BaseUrl    *string `json:"base_url,omitempty"`
	Model      *string `json:"model,omitempty"`
	Provider   *string `json:"provider,omitempty"`
	ProviderId *string `json:"provider_id,omitempty"`
}

// MemoryInjectedEvent defines model for MemoryInjectedEvent.
type MemoryInjectedEvent struct {
	Memories []MemoryWire `json:"memories"`
	Type     string       `json:"type"`
}

// MemoryLifecycleSettings defines model for MemoryLifecycleSettings.
type MemoryLifecycleSettings struct {
	CompactionOnExtract   *bool    `json:"compaction_on_extract,omitempty"`
	CompactionTargetRatio *float32 `json:"compaction_target_ratio,omitempty"`
	DecayHalfLifeDays     *float32 `json:"decay_half_life_days,omitempty"`
	ForgetThreshold       *float32 `json:"forget_threshold,omitempty"`
	MaxMemories           *int     `json:"max_memories,omitempty"`
	MaxUsageBoost         *float32 `json:"max_usage_boost,omitempty"`
	UsageBoostFactor      *float32 `json:"usage_boost_factor,omitempty"`
}

// MemoryResource defines model for MemoryResource.
type MemoryResource struct {
	AccessCount int64   `json:"access_count"`
	BaseWeight  float32 `json:"base_weight"`
	Content     string  `json:"content"`

	// CreatedAt Unix epoch milliseconds.
	CreatedAt       int64   `json:"created_at"`
	EffectiveWeight float32 `json:"effective_weight"`
	Id              string  `json:"id"`
	Kind            string  `json:"kind"`

	// LastAccessedAt Unix epoch milliseconds.
	LastAccessedAt *int64   `json:"last_accessed_at,omitempty"`
	Pinned         bool     `json:"pinned"`
	Scope          string   `json:"scope"`
	Similarity     *float32 `json:"similarity,omitempty"`
	Source         string   `json:"source"`

	// UpdatedAt Unix epoch milliseconds.
	UpdatedAt int64 `json:"updated_at"`
}

// MemorySettings defines model for MemorySettings.
type MemorySettings struct {
	AutoExtract         *bool                    `json:"auto_extract,omitempty"`
	AutoRetrieve        *bool                    `json:"auto_retrieve,omitempty"`
	Embedding           *MemoryEmbeddingSettings `json:"embedding,omitempty"`
	Enabled             *bool                    `json:"enabled,omitempty"`
	ExtractionModel     *string                  `json:"extraction_model,omitempty"`
	ExtractionProvider  *string                  `json:"extraction_provider,omitempty"`
	Lifecycle           *MemoryLifecycleSettings `json:"lifecycle,omitempty"`
	MaxRetrieved        *int                     `json:"max_retrieved,omitempty"`
	SimilarityThreshold *float32                 `json:"similarity_threshold,omitempty"`
}

// MemoryUpdatedEvent defines model for MemoryUpdatedEvent.
type MemoryUpdatedEvent struct {
	Changes []MemoryChangeWire `json:"changes"`
	Type    string             `json:"type"`
}

// MemoryWire defines model for MemoryWire.
type MemoryWire struct {
	Content         string  `json:"content"`
	EffectiveWeight float32 `json:"effective_weight"`
	Id              string  `json:"id"`
	Kind            string  `json:"kind"`
	Similarity      float32 `json:"similarity"`
}

// PostMessageRequest defines model for PostMessageRequest.
type PostMessageRequest struct {
	// FilePaths Workspace-relative file paths to include as context. Each file must be a readable text file at most 256 KB.
	FilePaths *[]string `json:"file_paths,omitempty"`

	// Images Optional base64 image attachments. Supported media types are image/png, image/jpeg, image/gif, and image/webp.
	Images *[]ImageAttachment `json:"images,omitempty"`

	// Text User input text. Required when images is empty.
	Text *string `json:"text,omitempty"`
}

// PruneWorkspacesResponse defines model for PruneWorkspacesResponse.
type PruneWorkspacesResponse struct {
	// Pruned Number of workspace registrations removed from the database.
	Pruned int `json:"pruned"`
}

// PurgeArchivedMemoryRequest defines model for PurgeArchivedMemoryRequest.
type PurgeArchivedMemoryRequest struct {
	OlderThanDays int `json:"older_than_days"`
}

// PurgeArchivedMemoryResponse defines model for PurgeArchivedMemoryResponse.
type PurgeArchivedMemoryResponse struct {
	MemoriesPurged     int    `json:"memories_purged"`
	MemoryEventsPurged int    `json:"memory_events_purged"`
	Status             string `json:"status"`
}

// ReasoningDeltaEvent defines model for ReasoningDeltaEvent.
type ReasoningDeltaEvent struct {
	Text string `json:"text"`
	Type string `json:"type"`
}

// ReasoningStartEvent defines model for ReasoningStartEvent.
type ReasoningStartEvent struct {
	Type string `json:"type"`
}

// SearchMemoryRequest defines model for SearchMemoryRequest.
type SearchMemoryRequest struct {
	Limit *int   `json:"limit,omitempty"`
	Query string `json:"query"`
}

// Session defines model for Session.
type Session struct {
	// AcpSessionId External ACP session ID recorded for diagnostics.
	AcpSessionId *string `json:"acp_session_id,omitempty"`

	// CreatedAt Unix epoch milliseconds.
	CreatedAt        int64                    `json:"created_at"`
	DelegationStatus *SessionDelegationStatus `json:"delegation_status,omitempty"`
	Id               string                   `json:"id"`
	ModelId          string                   `json:"model_id"`

	// OutputSummary Final summary from a delegated child session.
	OutputSummary *string `json:"output_summary,omitempty"`

	// ParentSessionId Parent session ID for delegated child sessions.
	ParentSessionId *string `json:"parent_session_id,omitempty"`

	// PendingQuestion Legacy field retained for persisted child session compatibility.
	PendingQuestion *string `json:"pending_question,omitempty"`
	ProviderId      string  `json:"provider_id"`

	// Purpose Delegation task purpose for child sessions.
	Purpose    *string       `json:"purpose,omitempty"`
	Status     SessionStatus `json:"status"`
	Title      string        `json:"title"`
	TokenUsage TokenUsage    `json:"token_usage"`

	// UpdatedAt Unix epoch milliseconds.
	UpdatedAt     int64  `json:"updated_at"`
	WorkspaceId   string `json:"workspace_id"`
	WorkspacePath string `json:"workspace_path"`
}

// SessionDelegationStatus defines model for Session.DelegationStatus.
type SessionDelegationStatus string

// SessionStatus defines model for Session.Status.
type SessionStatus string

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	Sessions []Session `json:"sessions"`
}

// SimpleErrorResponse defines model for SimpleErrorResponse.
type SimpleErrorResponse struct {
	Error string `json:"error"`
}

// Skill defines model for Skill.
type Skill struct {
	CanDelete   bool   `json:"can_delete"`
	CanExport   bool   `json:"can_export"`
	Description string `json:"description"`
	Internal    bool   `json:"internal"`
	IsSymlink   bool   `json:"is_symlink"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Source      string `json:"source"`
}

// SkillDetailResponse defines model for SkillDetailResponse.
type SkillDetailResponse struct {
	Content string `json:"content"`
	Skill   Skill  `json:"skill"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// StepFinishEvent defines model for StepFinishEvent.
type StepFinishEvent struct {
	Type  string     `json:"type"`
	Usage TokenUsage `json:"usage"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	union json.RawMessage
}

// SubagentFinishedEvent defines model for SubagentFinishedEvent.
type SubagentFinishedEvent struct {
	ChildSessionId   string `json:"child_session_id"`
	DelegationStatus string `json:"delegation_status"`
	Summary          string `json:"summary"`
	Type             string `json:"type"`
}

// SubagentProgressEvent defines model for SubagentProgressEvent.
type SubagentProgressEvent struct {
	ChildSessionId string `json:"child_session_id"`
	ProgressKind   string `json:"progress_kind"`
	ProgressText   string `json:"progress_text"`
	Type           string `json:"type"`
}

// SubagentStartedEvent defines model for SubagentStartedEvent.
type SubagentStartedEvent struct {
	AgentName      string `json:"agent_name"`
	ChildSessionId string `json:"child_session_id"`
	Purpose        string `json:"purpose"`
	Type           string `json:"type"`
}

// SyncSkillsResponse defines model for SyncSkillsResponse.
type SyncSkillsResponse struct {
	Created []string  `json:"created"`
	Errors  *[]string `json:"errors,omitempty"`
	Skipped []string  `json:"skipped"`
}

// TextDeltaEvent defines model for TextDeltaEvent.
type TextDeltaEvent struct {
	Delta string `json:"delta"`
	Type  string `json:"type"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	CacheRead    int `json:"cache_read"`
	CacheWrite   int `json:"cache_write"`
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// ToolCallEvent defines model for ToolCallEvent.
type ToolCallEvent struct {
	Id    string                 `json:"id"`
	Input map[string]interface{} `json:"input"`
	Tool  string                 `json:"tool"`
	Type  string                 `json:"type"`
}

// ToolResultEvent defines model for ToolResultEvent.
type ToolResultEvent struct {
	Error  *string `json:"error,omitempty"`
	Id     string  `json:"id"`
	Output string  `json:"output"`
	Tool   string  `json:"tool"`
	Type   string  `json:"type"`
}

// TranscriptItem defines model for TranscriptItem.
type TranscriptItem struct {
	Images *[]ImageAttachment `json:"images,omitempty"`

	// Memories Injected memories surfaced for a memory transcript item.
	Memories  *[]MemoryWire `json:"memories,omitempty"`
	Text      *string       `json:"text,omitempty"`
	ToolError *bool         `json:"tool_error,omitempty"`

	// ToolInput Opaque JSON tool input.
	ToolInput  interface{}        `json:"tool_input,omitempty"`
	ToolName   *string            `json:"tool_name,omitempty"`
	ToolOutput *string            `json:"tool_output,omitempty"`
	Type       TranscriptItemType `json:"type"`
}

// TranscriptItemType defines model for TranscriptItem.Type.
type TranscriptItemType string

// TranscriptResponse defines model for TranscriptResponse.
type TranscriptResponse struct {
	Items     []TranscriptItem `json:"items"`
	SessionId string           `json:"session_id"`
}

// UpdateMemoryRequest defines model for UpdateMemoryRequest.
type UpdateMemoryRequest struct {
	BaseWeight *float32 `json:"base_weight,omitempty"`
	Content    *string  `json:"content,omitempty"`
	Kind       *string  `json:"kind,omitempty"`
	Pinned     *bool    `json:"pinned,omitempty"`
}

// UpdateSessionRequest defines model for UpdateSessionRequest.
type UpdateSessionRequest struct {
	ModelId    string `json:"model_id"`
	ProviderId string `json:"provider_id"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	Id   string `json:"id"`
	Path string `json:"path"`
}

// WorkspaceFileContent defines model for WorkspaceFileContent.
type WorkspaceFileContent struct {
	union json.RawMessage
}

// WorkspaceFileImageContent defines model for WorkspaceFileImageContent.
type WorkspaceFileImageContent struct {
	DataUrl  string                        `json:"data_url"`
	Kind     WorkspaceFileImageContentKind `json:"kind"`
	MimeType string                        `json:"mime_type"`
}

// WorkspaceFileImageContentKind defines model for WorkspaceFileImageContent.Kind.
type WorkspaceFileImageContentKind string

// WorkspaceFileList defines model for WorkspaceFileList.
type WorkspaceFileList struct {
	// Files Workspace-relative file paths.
	Files []string `json:"files"`

	// Truncated True when more matching files exist than the limit returned. Narrow with the q query parameter to find files not in this page.
	Truncated *bool `json:"truncated,omitempty"`
}

// WorkspaceFileTextContent defines model for WorkspaceFileTextContent.
type WorkspaceFileTextContent struct {
	Content   string                       `json:"content"`
	Extension string                       `json:"extension"`
	Kind      WorkspaceFileTextContentKind `json:"kind"`
}

// WorkspaceFileTextContentKind defines model for WorkspaceFileTextContent.Kind.
type WorkspaceFileTextContentKind string

// WorkspaceListResponse defines model for WorkspaceListResponse.
type WorkspaceListResponse struct {
	Workspaces []Workspace `json:"workspaces"`
}

// WriteWorkspaceFileRequest Provide either `workspace_id` or `workspace_path`.
type WriteWorkspaceFileRequest struct {
	// Content UTF-8 text content to write.
	Content string `json:"content"`

	// Path Workspace-relative file path.
	Path string `json:"path"`

	// WorkspaceId Registered workspace identifier.
	WorkspaceId *string `json:"workspace_id,omitempty"`

	// WorkspacePath Absolute filesystem path for the workspace.
	WorkspacePath *string `json:"workspace_path,omitempty"`
}

// SessionId defines model for SessionId.
type SessionId = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// WorkspaceId Registered workspace identifier.
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`

	// WorkspacePath Absolute workspace path for an already-registered workspace.
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`

	// All When true, returns top-level sessions across all workspaces and ignores workspace scope.
	All *bool `form:"all,omitempty" json:"all,omitempty"`
}

// ListSkillsParams defines parameters for ListSkills.
type ListSkillsParams struct {
	// WorkspacePath Optional workspace path used to include project-local skill roots.
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`
}

// SyncSkillsParams defines parameters for SyncSkills.
type SyncSkillsParams struct {
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`
}

// DeleteSkillParams defines parameters for DeleteSkill.
type DeleteSkillParams struct {
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`
}

// GetSkillParams defines parameters for GetSkill.
type GetSkillParams struct {
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`
}

// ExportSkillParams defines parameters for ExportSkill.
type ExportSkillParams struct {
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`
}

// ListWorkspaceFilesParams defines parameters for ListWorkspaceFiles.
type ListWorkspaceFilesParams struct {
	// WorkspaceId Registered workspace identifier.
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`

	// WorkspacePath Absolute workspace path for an already-registered workspace.
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`

	// Q Optional substring filter on the relative file path.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Limit Maximum number of results to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ReadWorkspaceFileContentParams defines parameters for ReadWorkspaceFileContent.
type ReadWorkspaceFileContentParams struct {
	WorkspaceId   *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
	WorkspacePath *string `form:"workspace_path,omitempty" json:"workspace_path,omitempty"`

	// Path Workspace-relative file path.
	Path string `form:"path" json:"path"`
}

// CreateMemoryJSONRequestBody defines body for CreateMemory for application/json ContentType.
type CreateMemoryJSONRequestBody = CreateMemoryRequest

// SearchMemoriesJSONRequestBody defines body for SearchMemories for application/json ContentType.
type SearchMemoriesJSONRequestBody = SearchMemoryRequest

// PatchMemoryJSONRequestBody defines body for PatchMemory for application/json ContentType.
type PatchMemoryJSONRequestBody = UpdateMemoryRequest

// PurgeArchivedMemoryJSONRequestBody defines body for PurgeArchivedMemory for application/json ContentType.
type PurgeArchivedMemoryJSONRequestBody = PurgeArchivedMemoryRequest

// PutMemorySettingsJSONRequestBody defines body for PutMemorySettings for application/json ContentType.
type PutMemorySettingsJSONRequestBody = MemorySettings

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// PatchSessionJSONRequestBody defines body for PatchSession for application/json ContentType.
type PatchSessionJSONRequestBody = UpdateSessionRequest

// ForkSessionJSONRequestBody defines body for ForkSession for application/json ContentType.
type ForkSessionJSONRequestBody = ForkSessionRequest

// PostSessionMessageJSONRequestBody defines body for PostSessionMessage for application/json ContentType.
type PostSessionMessageJSONRequestBody = PostMessageRequest

// ChangeSessionWorkspaceJSONRequestBody defines body for ChangeSessionWorkspace for application/json ContentType.
type ChangeSessionWorkspaceJSONRequestBody = ChangeSessionWorkspaceRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// WriteWorkspaceFileContentJSONRequestBody defines body for WriteWorkspaceFileContent for application/json ContentType.
type WriteWorkspaceFileContentJSONRequestBody = WriteWorkspaceFileRequest

// AsTextDeltaEvent returns the union data inside the StreamEvent as a TextDeltaEvent
func (t StreamEvent) AsTextDeltaEvent() (TextDeltaEvent, error) {
	var body TextDeltaEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextDeltaEvent overwrites any union data inside the StreamEvent as the provided TextDeltaEvent
func (t *StreamEvent) FromTextDeltaEvent(v TextDeltaEvent) error {
	v.Type = "text_delta"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextDeltaEvent performs a merge with any union data inside the StreamEvent, using the provided TextDeltaEvent
func (t *StreamEvent) MergeTextDeltaEvent(v TextDeltaEvent) error {
	v.Type = "text_delta"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReasoningStartEvent returns the union data inside the StreamEvent as a ReasoningStartEvent
func (t StreamEvent) AsReasoningStartEvent() (ReasoningStartEvent, error) {
	var body ReasoningStartEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReasoningStartEvent overwrites any union data inside the StreamEvent as the provided ReasoningStartEvent
func (t *StreamEvent) FromReasoningStartEvent(v ReasoningStartEvent) error {
	v.Type = "reasoning_start"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReasoningStartEvent performs a merge with any union data inside the StreamEvent, using the provided ReasoningStartEvent
func (t *StreamEvent) MergeReasoningStartEvent(v ReasoningStartEvent) error {
	v.Type = "reasoning_start"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReasoningDeltaEvent returns the union data inside the StreamEvent as a ReasoningDeltaEvent
func (t StreamEvent) AsReasoningDeltaEvent() (ReasoningDeltaEvent, error) {
	var body ReasoningDeltaEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReasoningDeltaEvent overwrites any union data inside the StreamEvent as the provided ReasoningDeltaEvent
func (t *StreamEvent) FromReasoningDeltaEvent(v ReasoningDeltaEvent) error {
	v.Type = "reasoning_delta"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReasoningDeltaEvent performs a merge with any union data inside the StreamEvent, using the provided ReasoningDeltaEvent
func (t *StreamEvent) MergeReasoningDeltaEvent(v ReasoningDeltaEvent) error {
	v.Type = "reasoning_delta"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolCallEvent returns the union data inside the StreamEvent as a ToolCallEvent
func (t StreamEvent) AsToolCallEvent() (ToolCallEvent, error) {
	var body ToolCallEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolCallEvent overwrites any union data inside the StreamEvent as the provided ToolCallEvent
func (t *StreamEvent) FromToolCallEvent(v ToolCallEvent) error {
	v.Type = "tool_call"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolCallEvent performs a merge with any union data inside the StreamEvent, using the provided ToolCallEvent
func (t *StreamEvent) MergeToolCallEvent(v ToolCallEvent) error {
	v.Type = "tool_call"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolResultEvent returns the union data inside the StreamEvent as a ToolResultEvent
func (t StreamEvent) AsToolResultEvent() (ToolResultEvent, error) {
	var body ToolResultEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolResultEvent overwrites any union data inside the StreamEvent as the provided ToolResultEvent
func (t *StreamEvent) FromToolResultEvent(v ToolResultEvent) error {
	v.Type = "tool_result"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolResultEvent performs a merge with any union data inside the StreamEvent, using the provided ToolResultEvent
func (t *StreamEvent) MergeToolResultEvent(v ToolResultEvent) error {
	v.Type = "tool_result"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStepFinishEvent returns the union data inside the StreamEvent as a StepFinishEvent
func (t StreamEvent) AsStepFinishEvent() (StepFinishEvent, error) {
	var body StepFinishEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStepFinishEvent overwrites any union data inside the StreamEvent as the provided StepFinishEvent
func (t *StreamEvent) FromStepFinishEvent(v StepFinishEvent) error {
	v.Type = "step_finish"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStepFinishEvent performs a merge with any union data inside the StreamEvent, using the provided StepFinishEvent
func (t *StreamEvent) MergeStepFinishEvent(v StepFinishEvent) error {
	v.Type = "step_finish"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubagentStartedEvent returns the union data inside the StreamEvent as a SubagentStartedEvent
func (t StreamEvent) AsSubagentStartedEvent() (SubagentStartedEvent, error) {
	var body SubagentStartedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubagentStartedEvent overwrites any union data inside the StreamEvent as the provided SubagentStartedEvent
func (t *StreamEvent) FromSubagentStartedEvent(v SubagentStartedEvent) error {
	v.Type = "subagent_started"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubagentStartedEvent performs a merge with any union data inside the StreamEvent, using the provided SubagentStartedEvent
func (t *StreamEvent) MergeSubagentStartedEvent(v SubagentStartedEvent) error {
	v.Type = "subagent_started"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubagentProgressEvent returns the union data inside the StreamEvent as a SubagentProgressEvent
func (t StreamEvent) AsSubagentProgressEvent() (SubagentProgressEvent, error) {
	var body SubagentProgressEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubagentProgressEvent overwrites any union data inside the StreamEvent as the provided SubagentProgressEvent
func (t *StreamEvent) FromSubagentProgressEvent(v SubagentProgressEvent) error {
	v.Type = "subagent_progress"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubagentProgressEvent performs a merge with any union data inside the StreamEvent, using the provided SubagentProgressEvent
func (t *StreamEvent) MergeSubagentProgressEvent(v SubagentProgressEvent) error {
	v.Type = "subagent_progress"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubagentFinishedEvent returns the union data inside the StreamEvent as a SubagentFinishedEvent
func (t StreamEvent) AsSubagentFinishedEvent() (SubagentFinishedEvent, error) {
	var body SubagentFinishedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubagentFinishedEvent overwrites any union data inside the StreamEvent as the provided SubagentFinishedEvent
func (t *StreamEvent) FromSubagentFinishedEvent(v SubagentFinishedEvent) error {
	v.Type = "subagent_finished"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubagentFinishedEvent performs a merge with any union data inside the StreamEvent, using the provided SubagentFinishedEvent
func (t *StreamEvent) MergeSubagentFinishedEvent(v SubagentFinishedEvent) error {
	v.Type = "subagent_finished"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMemoryInjectedEvent returns the union data inside the StreamEvent as a MemoryInjectedEvent
func (t StreamEvent) AsMemoryInjectedEvent() (MemoryInjectedEvent, error) {
	var body MemoryInjectedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMemoryInjectedEvent overwrites any union data inside the StreamEvent as the provided MemoryInjectedEvent
func (t *StreamEvent) FromMemoryInjectedEvent(v MemoryInjectedEvent) error {
	v.Type = "memory_injected"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMemoryInjectedEvent performs a merge with any union data inside the StreamEvent, using the provided MemoryInjectedEvent
func (t *StreamEvent) MergeMemoryInjectedEvent(v MemoryInjectedEvent) error {
	v.Type = "memory_injected"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMemoryUpdatedEvent returns the union data inside the StreamEvent as a MemoryUpdatedEvent
func (t StreamEvent) AsMemoryUpdatedEvent() (MemoryUpdatedEvent, error) {
	var body MemoryUpdatedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMemoryUpdatedEvent overwrites any union data inside the StreamEvent as the provided MemoryUpdatedEvent
func (t *StreamEvent) FromMemoryUpdatedEvent(v MemoryUpdatedEvent) error {
	v.Type = "memory_updated"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMemoryUpdatedEvent performs a merge with any union data inside the StreamEvent, using the provided MemoryUpdatedEvent
func (t *StreamEvent) MergeMemoryUpdatedEvent(v MemoryUpdatedEvent) error {
	v.Type = "memory_updated"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorEvent returns the union data inside the StreamEvent as a ErrorEvent
func (t StreamEvent) AsErrorEvent() (ErrorEvent, error) {
	var body ErrorEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorEvent overwrites any union data inside the StreamEvent as the provided ErrorEvent
func (t *StreamEvent) FromErrorEvent(v ErrorEvent) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorEvent performs a merge with any union data inside the StreamEvent, using the provided ErrorEvent
func (t *StreamEvent) MergeErrorEvent(v ErrorEvent) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDoneEvent returns the union data inside the StreamEvent as a DoneEvent
func (t StreamEvent) AsDoneEvent() (DoneEvent, error) {
	var body DoneEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDoneEvent overwrites any union data inside the StreamEvent as the provided DoneEvent
func (t *StreamEvent) FromDoneEvent(v DoneEvent) error {
	v.Type = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDoneEvent performs a merge with any union data inside the StreamEvent, using the provided DoneEvent
func (t *StreamEvent) MergeDoneEvent(v DoneEvent) error {
	v.Type = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t StreamEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "done":
		return t.AsDoneEvent()
	case "error":
		return t.AsErrorEvent()
	case "memory_injected":
		return t.AsMemoryInjectedEvent()
	case "memory_updated":
		return t.AsMemoryUpdatedEvent()
	case "reasoning_delta":
		return t.AsReasoningDeltaEvent()
	case "reasoning_start":
		return t.AsReasoningStartEvent()
	case "step_finish":
		return t.AsStepFinishEvent()
	case "subagent_finished":
		return t.AsSubagentFinishedEvent()
	case "subagent_progress":
		return t.AsSubagentProgressEvent()
	case "subagent_started":
		return t.AsSubagentStartedEvent()
	case "text_delta":
		return t.AsTextDeltaEvent()
	case "tool_call":
		return t.AsToolCallEvent()
	case "tool_result":
		return t.AsToolResultEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t StreamEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsWorkspaceFileTextContent returns the union data inside the WorkspaceFileContent as a WorkspaceFileTextContent
func (t WorkspaceFileContent) AsWorkspaceFileTextContent() (WorkspaceFileTextContent, error) {
	var body WorkspaceFileTextContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkspaceFileTextContent overwrites any union data inside the WorkspaceFileContent as the provided WorkspaceFileTextContent
func (t *WorkspaceFileContent) FromWorkspaceFileTextContent(v WorkspaceFileTextContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkspaceFileTextContent performs a merge with any union data inside the WorkspaceFileContent, using the provided WorkspaceFileTextContent
func (t *WorkspaceFileContent) MergeWorkspaceFileTextContent(v WorkspaceFileTextContent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkspaceFileImageContent returns the union data inside the WorkspaceFileContent as a WorkspaceFileImageContent
func (t WorkspaceFileContent) AsWorkspaceFileImageContent() (WorkspaceFileImageContent, error) {
	var body WorkspaceFileImageContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkspaceFileImageContent overwrites any union data inside the WorkspaceFileContent as the provided WorkspaceFileImageContent
func (t *WorkspaceFileContent) FromWorkspaceFileImageContent(v WorkspaceFileImageContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkspaceFileImageContent performs a merge with any union data inside the WorkspaceFileContent, using the provided WorkspaceFileImageContent
func (t *WorkspaceFileContent) MergeWorkspaceFileImageContent(v WorkspaceFileImageContent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WorkspaceFileContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WorkspaceFileContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
