// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway.sql

package db

import (
	"context"
)

const getGatewaySession = `-- name: GetGatewaySession :one
SELECT id, platform, platform_user_id, platform_channel_id, thread_id, cometmind_session_id, workspace_id, last_active_at
FROM gateway_sessions
WHERE
    platform = ?
    AND platform_user_id = ?
    AND platform_channel_id = ?
    AND thread_id = ?
LIMIT 1
`

type GetGatewaySessionParams struct {
	Platform          string `json:"platform"`
	PlatformUserID    string `json:"platform_user_id"`
	PlatformChannelID string `json:"platform_channel_id"`
	ThreadID          string `json:"thread_id"`
}

func (q *Queries) GetGatewaySession(ctx context.Context, arg GetGatewaySessionParams) (GatewaySession, error) {
	row := q.db.QueryRowContext(ctx, getGatewaySession,
		arg.Platform,
		arg.PlatformUserID,
		arg.PlatformChannelID,
		arg.ThreadID,
	)
	var i GatewaySession
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.PlatformUserID,
		&i.PlatformChannelID,
		&i.ThreadID,
		&i.CometmindSessionID,
		&i.WorkspaceID,
		&i.LastActiveAt,
	)
	return i, err
}

const updateGatewaySessionWorkspace = `-- name: UpdateGatewaySessionWorkspace :exec
UPDATE gateway_sessions
SET
    workspace_id = ?,
    last_active_at = unixepoch ('now', 'subsec') * 1000
WHERE cometmind_session_id = ?
`

type UpdateGatewaySessionWorkspaceParams struct {
	WorkspaceID        string `json:"workspace_id"`
	CometmindSessionID string `json:"cometmind_session_id"`
}

func (q *Queries) UpdateGatewaySessionWorkspace(ctx context.Context, arg UpdateGatewaySessionWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateGatewaySessionWorkspace, arg.WorkspaceID, arg.CometmindSessionID)
	return err
}

const upsertGatewaySession = `-- name: UpsertGatewaySession :one
INSERT INTO gateway_sessions (
    id,
    platform,
    platform_user_id,
    platform_channel_id,
    thread_id,
    cometmind_session_id,
    workspace_id,
    last_active_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch ('now', 'subsec') * 1000)
ON CONFLICT (
    platform,
    platform_user_id,
    platform_channel_id,
    thread_id
) DO UPDATE SET
    cometmind_session_id = excluded.cometmind_session_id,
    workspace_id = excluded.workspace_id,
    last_active_at = unixepoch ('now', 'subsec') * 1000
RETURNING id, platform, platform_user_id, platform_channel_id, thread_id, cometmind_session_id, workspace_id, last_active_at
`

type UpsertGatewaySessionParams struct {
	ID                 string `json:"id"`
	Platform           string `json:"platform"`
	PlatformUserID     string `json:"platform_user_id"`
	PlatformChannelID  string `json:"platform_channel_id"`
	ThreadID           string `json:"thread_id"`
	CometmindSessionID string `json:"cometmind_session_id"`
	WorkspaceID        string `json:"workspace_id"`
}

func (q *Queries) UpsertGatewaySession(ctx context.Context, arg UpsertGatewaySessionParams) (GatewaySession, error) {
	row := q.db.QueryRowContext(ctx, upsertGatewaySession,
		arg.ID,
		arg.Platform,
		arg.PlatformUserID,
		arg.PlatformChannelID,
		arg.ThreadID,
		arg.CometmindSessionID,
		arg.WorkspaceID,
	)
	var i GatewaySession
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.PlatformUserID,
		&i.PlatformChannelID,
		&i.ThreadID,
		&i.CometmindSessionID,
		&i.WorkspaceID,
		&i.LastActiveAt,
	)
	return i, err
}
