// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Message struct {
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	Role             string `json:"role"`
	Content          string `json:"content"`
	ReasoningContent string `json:"reasoning_content"`
	TokenCount       int64  `json:"token_count"`
	CreatedAt        int64  `json:"created_at"`
}

type Session struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Title       string `json:"title"`
	ModelID     string `json:"model_id"`
	ProviderID  string `json:"provider_id"`
	Status      string `json:"status"`
	TokenUsage  string `json:"token_usage"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type ToolCall struct {
	ID         string        `json:"id"`
	MessageID  string        `json:"message_id"`
	ToolName   string        `json:"tool_name"`
	Arguments  string        `json:"arguments"`
	Result     string        `json:"result"`
	DurationMs int64         `json:"duration_ms"`
	ExitCode   sql.NullInt64 `json:"exit_code"`
	CreatedAt  int64         `json:"created_at"`
}

type Workspace struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	CreatedAt int64  `json:"created_at"`
}
