// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, workspace_id, title, model_id, provider_id, status)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, title, model_id, provider_id, status, token_usage, created_at, updated_at
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Title       string `json:"title"`
	ModelID     string `json:"model_id"`
	ProviderID  string `json:"provider_id"`
	Status      string `json:"status"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.ModelID,
		arg.ProviderID,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.ModelID,
		&i.ProviderID,
		&i.Status,
		&i.TokenUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, created_at, updated_at
FROM sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.ModelID,
		&i.ProviderID,
		&i.Status,
		&i.TokenUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByWorkspace = `-- name: ListSessionsByWorkspace :many
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, created_at, updated_at
FROM sessions
WHERE workspace_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByWorkspace(ctx context.Context, workspaceID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.ModelID,
			&i.ProviderID,
			&i.Status,
			&i.TokenUsage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateSessionModel = `-- name: UpdateSessionModel :exec
UPDATE sessions
SET
    model_id = ?,
    provider_id = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionModelParams struct {
	ModelID    string `json:"model_id"`
	ProviderID string `json:"provider_id"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionModel, arg.ModelID, arg.ProviderID, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET
    title = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle, arg.Title, arg.ID)
	return err
}

const updateSessionTokenUsage = `-- name: UpdateSessionTokenUsage :exec
UPDATE sessions
SET
    token_usage = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionTokenUsageParams struct {
	TokenUsage string `json:"token_usage"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSessionTokenUsage(ctx context.Context, arg UpdateSessionTokenUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTokenUsage, arg.TokenUsage, arg.ID)
	return err
}
