// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_calls.sql

package db

import (
	"context"
	"database/sql"
)

const createToolCall = `-- name: CreateToolCall :one
INSERT INTO tool_calls (
    id,
    message_id,
    tool_name,
    arguments,
    result,
    duration_ms,
    exit_code
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, message_id, tool_name, arguments, result, duration_ms, exit_code, created_at
`

type CreateToolCallParams struct {
	ID         string        `json:"id"`
	MessageID  string        `json:"message_id"`
	ToolName   string        `json:"tool_name"`
	Arguments  string        `json:"arguments"`
	Result     string        `json:"result"`
	DurationMs int64         `json:"duration_ms"`
	ExitCode   sql.NullInt64 `json:"exit_code"`
}

func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error) {
	row := q.db.QueryRowContext(ctx, createToolCall,
		arg.ID,
		arg.MessageID,
		arg.ToolName,
		arg.Arguments,
		arg.Result,
		arg.DurationMs,
		arg.ExitCode,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ToolName,
		&i.Arguments,
		&i.Result,
		&i.DurationMs,
		&i.ExitCode,
		&i.CreatedAt,
	)
	return i, err
}

const listToolCallsByMessage = `-- name: ListToolCallsByMessage :many
SELECT id, message_id, tool_name, arguments, result, duration_ms, exit_code, created_at
FROM tool_calls
WHERE message_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListToolCallsByMessage(ctx context.Context, messageID string) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listToolCallsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ToolName,
			&i.Arguments,
			&i.Result,
			&i.DurationMs,
			&i.ExitCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToolCallResult = `-- name: UpdateToolCallResult :exec
UPDATE tool_calls
SET
    result = ?,
    duration_ms = ?,
    exit_code = ?
WHERE id = ?
`

type UpdateToolCallResultParams struct {
	Result     string        `json:"result"`
	DurationMs int64         `json:"duration_ms"`
	ExitCode   sql.NullInt64 `json:"exit_code"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateToolCallResult(ctx context.Context, arg UpdateToolCallResultParams) error {
	_, err := q.db.ExecContext(ctx, updateToolCallResult,
		arg.Result,
		arg.DurationMs,
		arg.ExitCode,
		arg.ID,
	)
	return err
}
