// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, path)
VALUES (?, ?, ?)
RETURNING id, name, path, created_at
`

type CreateWorkspaceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.ID, arg.Name, arg.Path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, path, created_at
FROM workspaces
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByPath = `-- name: GetWorkspaceByPath :one
SELECT id, name, path, created_at
FROM workspaces
WHERE path = ?
LIMIT 1
`

func (q *Queries) GetWorkspaceByPath(ctx context.Context, path string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByPath, path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}
