// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :execrows
UPDATE jobs
SET
    status = 'ongoing',
    assigned_session_id = ?,
    lease_expires_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'todo'
  AND deleted_at IS NULL
  AND assigned_session_id IS NULL
`

type ClaimJobParams struct {
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimJob,
		arg.AssignedSessionID,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET
    status = 'done',
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
`

type CompleteJobParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeJob, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJob = `-- name: GetJob :one
SELECT id, description, definition_of_done, progress, status, priority, scheduled_at, due_at, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, deleted_at, created_at, updated_at
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DefinitionOfDone,
		&i.Progress,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.DueAt,
		&i.WorkspacePath,
		&i.AssignedSessionID,
		&i.LeaseExpiresAt,
		&i.CreatedBy,
		&i.SourceSessionID,
		&i.SourcePlatform,
		&i.SourceChannelID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByAssignedSession = `-- name: GetJobByAssignedSession :one
SELECT id, description, definition_of_done, progress, status, priority, scheduled_at, due_at, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, deleted_at, created_at, updated_at
FROM jobs
WHERE assigned_session_id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetJobByAssignedSession(ctx context.Context, assignedSessionID sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByAssignedSession, assignedSessionID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DefinitionOfDone,
		&i.Progress,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.DueAt,
		&i.WorkspacePath,
		&i.AssignedSessionID,
		&i.LeaseExpiresAt,
		&i.CreatedBy,
		&i.SourceSessionID,
		&i.SourcePlatform,
		&i.SourceChannelID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteJob = `-- name: HardDeleteJob :exec
DELETE FROM jobs
WHERE id = ?
`

func (q *Queries) HardDeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteJob, id)
	return err
}

const heartbeatJob = `-- name: HeartbeatJob :execrows
UPDATE jobs
SET
    lease_expires_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND assigned_session_id = ?
  AND deleted_at IS NULL
`

type HeartbeatJobParams struct {
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatJob,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.AssignedSessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (
    id,
    description,
    definition_of_done,
    progress,
    status,
    priority,
    scheduled_at,
    due_at,
    workspace_path,
    assigned_session_id,
    lease_expires_at,
    created_by,
    source_session_id,
    source_platform,
    source_channel_id,
    deleted_at,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertJobParams struct {
	ID                string         `json:"id"`
	Description       string         `json:"description"`
	DefinitionOfDone  string         `json:"definition_of_done"`
	Progress          string         `json:"progress"`
	Status            string         `json:"status"`
	Priority          int64          `json:"priority"`
	ScheduledAt       sql.NullInt64  `json:"scheduled_at"`
	DueAt             sql.NullInt64  `json:"due_at"`
	WorkspacePath     sql.NullString `json:"workspace_path"`
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	CreatedBy         string         `json:"created_by"`
	SourceSessionID   sql.NullString `json:"source_session_id"`
	SourcePlatform    string         `json:"source_platform"`
	SourceChannelID   sql.NullString `json:"source_channel_id"`
	DeletedAt         sql.NullInt64  `json:"deleted_at"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.Description,
		arg.DefinitionOfDone,
		arg.Progress,
		arg.Status,
		arg.Priority,
		arg.ScheduledAt,
		arg.DueAt,
		arg.WorkspacePath,
		arg.AssignedSessionID,
		arg.LeaseExpiresAt,
		arg.CreatedBy,
		arg.SourceSessionID,
		arg.SourcePlatform,
		arg.SourceChannelID,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertJobEvent = `-- name: InsertJobEvent :exec
INSERT INTO job_events (
    id,
    job_id,
    action,
    detail,
    actor_session_id,
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertJobEventParams struct {
	ID             string         `json:"id"`
	JobID          string         `json:"job_id"`
	Action         string         `json:"action"`
	Detail         string         `json:"detail"`
	ActorSessionID sql.NullString `json:"actor_session_id"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) error {
	_, err := q.db.ExecContext(ctx, insertJobEvent,
		arg.ID,
		arg.JobID,
		arg.Action,
		arg.Detail,
		arg.ActorSessionID,
		arg.CreatedAt,
	)
	return err
}

const listDeletedJobsBefore = `-- name: ListDeletedJobsBefore :many
SELECT id
FROM jobs
WHERE deleted_at IS NOT NULL
  AND deleted_at < ?
`

func (q *Queries) ListDeletedJobsBefore(ctx context.Context, deletedAt sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedJobsBefore, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, job_id, "action", detail, actor_session_id, created_at
FROM job_events
WHERE job_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID string) ([]JobEvent, error) {
	rows, err := q.db.QueryContext(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Action,
			&i.Detail,
			&i.ActorSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, description, definition_of_done, progress, status, priority, scheduled_at, due_at, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, deleted_at, created_at, updated_at
FROM jobs
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR status = ?1)
ORDER BY priority DESC, updated_at ASC
`

func (q *Queries) ListJobs(ctx context.Context, status interface{}) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.Progress,
			&i.Status,
			&i.Priority,
			&i.ScheduledAt,
			&i.DueAt,
			&i.WorkspacePath,
			&i.AssignedSessionID,
			&i.LeaseExpiresAt,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingJobs = `-- name: ListOngoingJobs :many
SELECT id, description, definition_of_done, progress, status, priority, scheduled_at, due_at, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, deleted_at, created_at, updated_at
FROM jobs
WHERE deleted_at IS NULL
  AND status = 'ongoing'
`

func (q *Queries) ListOngoingJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listOngoingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.Progress,
			&i.Status,
			&i.Priority,
			&i.ScheduledAt,
			&i.DueAt,
			&i.WorkspacePath,
			&i.AssignedSessionID,
			&i.LeaseExpiresAt,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyJobs = `-- name: ListReadyJobs :many
SELECT id, description, definition_of_done, progress, status, priority, scheduled_at, due_at, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, deleted_at, created_at, updated_at
FROM jobs
WHERE deleted_at IS NULL
  AND status = 'todo'
  AND (scheduled_at IS NULL OR scheduled_at <= ?)
ORDER BY priority DESC, updated_at ASC
`

func (q *Queries) ListReadyJobs(ctx context.Context, scheduledAt sql.NullInt64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listReadyJobs, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.Progress,
			&i.Status,
			&i.Priority,
			&i.ScheduledAt,
			&i.DueAt,
			&i.WorkspacePath,
			&i.AssignedSessionID,
			&i.LeaseExpiresAt,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseJob = `-- name: ReleaseJob :execrows
UPDATE jobs
SET
    status = 'todo',
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
`

type ReleaseJobParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseJob, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteJob = `-- name: SoftDeleteJob :execrows
UPDATE jobs
SET
    deleted_at = ?,
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    status = CASE WHEN status = 'ongoing' THEN 'todo' ELSE status END,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type SoftDeleteJobParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) SoftDeleteJob(ctx context.Context, arg SoftDeleteJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteJob, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJobProgress = `-- name: UpdateJobProgress :execrows
UPDATE jobs
SET
    progress = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
`

type UpdateJobProgressParams struct {
	Progress  string `json:"progress"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJobTodoFields = `-- name: UpdateJobTodoFields :execrows
UPDATE jobs
SET
    description = ?,
    definition_of_done = ?,
    priority = ?,
    scheduled_at = ?,
    due_at = ?,
    workspace_path = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'todo'
  AND deleted_at IS NULL
`

type UpdateJobTodoFieldsParams struct {
	Description      string         `json:"description"`
	DefinitionOfDone string         `json:"definition_of_done"`
	Priority         int64          `json:"priority"`
	ScheduledAt      sql.NullInt64  `json:"scheduled_at"`
	DueAt            sql.NullInt64  `json:"due_at"`
	WorkspacePath    sql.NullString `json:"workspace_path"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateJobTodoFields(ctx context.Context, arg UpdateJobTodoFieldsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobTodoFields,
		arg.Description,
		arg.DefinitionOfDone,
		arg.Priority,
		arg.ScheduledAt,
		arg.DueAt,
		arg.WorkspacePath,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
