// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createChildSession = `-- name: CreateChildSession :one
INSERT INTO sessions (
    id,
    workspace_id,
    title,
    model_id,
    provider_id,
    status,
    parent_session_id,
    purpose,
    delegation_status,
    output_summary
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
`

type CreateChildSessionParams struct {
	ID               string         `json:"id"`
	WorkspaceID      string         `json:"workspace_id"`
	Title            string         `json:"title"`
	ModelID          string         `json:"model_id"`
	ProviderID       string         `json:"provider_id"`
	Status           string         `json:"status"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Purpose          string         `json:"purpose"`
	DelegationStatus string         `json:"delegation_status"`
	OutputSummary    string         `json:"output_summary"`
}

func (q *Queries) CreateChildSession(ctx context.Context, arg CreateChildSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createChildSession,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.ModelID,
		arg.ProviderID,
		arg.Status,
		arg.ParentSessionID,
		arg.Purpose,
		arg.DelegationStatus,
		arg.OutputSummary,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.ModelID,
		&i.ProviderID,
		&i.Status,
		&i.TokenUsage,
		&i.ParentSessionID,
		&i.Purpose,
		&i.DelegationStatus,
		&i.OutputSummary,
		&i.AcpSessionID,
		&i.PendingQuestion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, workspace_id, title, model_id, provider_id, status)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Title       string `json:"title"`
	ModelID     string `json:"model_id"`
	ProviderID  string `json:"provider_id"`
	Status      string `json:"status"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.ModelID,
		arg.ProviderID,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.ModelID,
		&i.ProviderID,
		&i.Status,
		&i.TokenUsage,
		&i.ParentSessionID,
		&i.Purpose,
		&i.DelegationStatus,
		&i.OutputSummary,
		&i.AcpSessionID,
		&i.PendingQuestion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getActiveChildForParent = `-- name: GetActiveChildForParent :one
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
FROM sessions
WHERE
    parent_session_id = ?
    AND delegation_status = 'running'
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetActiveChildForParent(ctx context.Context, parentSessionID sql.NullString) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveChildForParent, parentSessionID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.ModelID,
		&i.ProviderID,
		&i.Status,
		&i.TokenUsage,
		&i.ParentSessionID,
		&i.Purpose,
		&i.DelegationStatus,
		&i.OutputSummary,
		&i.AcpSessionID,
		&i.PendingQuestion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
FROM sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.ModelID,
		&i.ProviderID,
		&i.Status,
		&i.TokenUsage,
		&i.ParentSessionID,
		&i.Purpose,
		&i.DelegationStatus,
		&i.OutputSummary,
		&i.AcpSessionID,
		&i.PendingQuestion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
FROM sessions
WHERE parent_session_id IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.ModelID,
			&i.ProviderID,
			&i.Status,
			&i.TokenUsage,
			&i.ParentSessionID,
			&i.Purpose,
			&i.DelegationStatus,
			&i.OutputSummary,
			&i.AcpSessionID,
			&i.PendingQuestion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildSessions = `-- name: ListChildSessions :many
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
FROM sessions
WHERE parent_session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listChildSessions, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.ModelID,
			&i.ProviderID,
			&i.Status,
			&i.TokenUsage,
			&i.ParentSessionID,
			&i.Purpose,
			&i.DelegationStatus,
			&i.OutputSummary,
			&i.AcpSessionID,
			&i.PendingQuestion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByWorkspace = `-- name: ListSessionsByWorkspace :many
SELECT id, workspace_id, title, model_id, provider_id, status, token_usage, parent_session_id, purpose, delegation_status, output_summary, acp_session_id, pending_question, created_at, updated_at
FROM sessions
WHERE workspace_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByWorkspace(ctx context.Context, workspaceID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.ModelID,
			&i.ProviderID,
			&i.Status,
			&i.TokenUsage,
			&i.ParentSessionID,
			&i.Purpose,
			&i.DelegationStatus,
			&i.OutputSummary,
			&i.AcpSessionID,
			&i.PendingQuestion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByWorkspaceAsc = `-- name: ListSessionsByWorkspaceAsc :many
SELECT id, updated_at, delegation_status
FROM sessions
WHERE workspace_id = ?
ORDER BY updated_at ASC
`

type ListSessionsByWorkspaceAscRow struct {
	ID               string `json:"id"`
	UpdatedAt        int64  `json:"updated_at"`
	DelegationStatus string `json:"delegation_status"`
}

func (q *Queries) ListSessionsByWorkspaceAsc(ctx context.Context, workspaceID string) ([]ListSessionsByWorkspaceAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByWorkspaceAsc, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByWorkspaceAscRow{}
	for rows.Next() {
		var i ListSessionsByWorkspaceAscRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt, &i.DelegationStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleSessionIDs = `-- name: ListStaleSessionIDs :many
SELECT id
FROM sessions
WHERE
    workspace_id = ?
    AND updated_at < ?
    AND delegation_status NOT IN (
        'pending',
        'running'
    )
ORDER BY updated_at ASC
`

type ListStaleSessionIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) ListStaleSessionIDs(ctx context.Context, arg ListStaleSessionIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStaleSessionIDs, arg.WorkspaceID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTitleIfEmpty = `-- name: SetTitleIfEmpty :exec
UPDATE sessions
SET
    title = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
  AND trim(title) = ''
`

type SetTitleIfEmptyParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

// Atomically sets title only when the current title is blank.
// The WHERE condition collapses the read-check-write into a single
// SQLite statement, eliminating the TOCTOU race in SetTitleIfEmpty.
func (q *Queries) SetTitleIfEmpty(ctx context.Context, arg SetTitleIfEmptyParams) error {
	_, err := q.db.ExecContext(ctx, setTitleIfEmpty, arg.Title, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateSessionACP = `-- name: UpdateSessionACP :exec
UPDATE sessions
SET
    acp_session_id = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionACPParams struct {
	AcpSessionID string `json:"acp_session_id"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSessionACP(ctx context.Context, arg UpdateSessionACPParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionACP, arg.AcpSessionID, arg.ID)
	return err
}

const updateSessionDelegation = `-- name: UpdateSessionDelegation :exec
UPDATE sessions
SET
    delegation_status = ?,
    output_summary = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionDelegationParams struct {
	DelegationStatus string `json:"delegation_status"`
	OutputSummary    string `json:"output_summary"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateSessionDelegation(ctx context.Context, arg UpdateSessionDelegationParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionDelegation, arg.DelegationStatus, arg.OutputSummary, arg.ID)
	return err
}

const updateSessionDelegationState = `-- name: UpdateSessionDelegationState :exec
UPDATE sessions
SET
    delegation_status = ?,
    output_summary = ?,
    pending_question = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionDelegationStateParams struct {
	DelegationStatus string `json:"delegation_status"`
	OutputSummary    string `json:"output_summary"`
	PendingQuestion  string `json:"pending_question"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateSessionDelegationState(ctx context.Context, arg UpdateSessionDelegationStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionDelegationState,
		arg.DelegationStatus,
		arg.OutputSummary,
		arg.PendingQuestion,
		arg.ID,
	)
	return err
}

const updateSessionModel = `-- name: UpdateSessionModel :exec
UPDATE sessions
SET
    model_id = ?,
    provider_id = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionModelParams struct {
	ModelID    string `json:"model_id"`
	ProviderID string `json:"provider_id"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionModel, arg.ModelID, arg.ProviderID, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET
    title = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle, arg.Title, arg.ID)
	return err
}

const updateSessionTokenUsage = `-- name: UpdateSessionTokenUsage :exec
UPDATE sessions
SET
    token_usage = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionTokenUsageParams struct {
	TokenUsage string `json:"token_usage"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSessionTokenUsage(ctx context.Context, arg UpdateSessionTokenUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTokenUsage, arg.TokenUsage, arg.ID)
	return err
}

const updateSessionWorkspace = `-- name: UpdateSessionWorkspace :exec
UPDATE sessions
SET
    workspace_id = ?,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE id = ?
`

type UpdateSessionWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateSessionWorkspace(ctx context.Context, arg UpdateSessionWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionWorkspace, arg.WorkspaceID, arg.ID)
	return err
}
